// Gerado automaticamente — logos hospedados no GitHub (128x128)
// Fonte: assets/logos/ via downloadLogos.js

const LOGOS = {
  'Flamengo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/flamengo.png',
  'Palmeiras': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/palmeiras.png',
  'Corinthians': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/corinthians.png',
  'Atletico Mineiro': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-mineiro.png',
  'Fluminense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/fluminense.png',
  'Botafogo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/botafogo.png',
  'Internacional': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/internacional.png',
  'Sao Paulo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sao-paulo.png',
  'Gremio': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/gremio.png',
  'Vasco da Gama': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/vasco-da-gama.png',
  'Bahia': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bahia.png',
  'Fortaleza': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/fortaleza.png',
  'Athletico Paranaense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/athletico-paranaense.png',
  'Cruzeiro': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cruzeiro.png',
  'Vitoria': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/vitoria.png',
  'Juventude': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/juventude.png',
  'RB Bragantino': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rb-bragantino.png',
  'Mirassol': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/mirassol.png',
  'Ceara': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ceara.png',
  'Sport Recife': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sport-recife.png',
  'America Mineiro': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/america-mineiro.png',
  'Goias': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/goias.png',
  'Cuiaba': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cuiaba.png',
  'Atletico Goianiense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-goianiense.png',
  'Criciuma': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/criciuma.png',
  'Coritiba': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/coritiba.png',
  'Ponte Preta': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ponte-preta.png',
  'Botafogo SP': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/botafogo-sp.png',
  'Operario Ferroviario': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/operario-ferroviario.png',
  'Paysandu': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/paysandu.png',
  'CRB': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/crb.png',
  'Avai': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/avai.png',
  'Amazonas': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/amazonas.png',
  'Vila Nova': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/vila-nova.png',
  'Novorizontino': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/novorizontino.png',
  'Chapecoense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/chapecoense.png',
  'Londrina': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/londrina.png',
  'Nautico': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nautico.png',
  'Guarani': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/guarani.png',
  'Sao Bernardo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sao-bernardo.png',
  'Santos': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/santos.png',
  'Remo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/remo.png',
  'Arsenal': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/arsenal.png',
  'Aston Villa': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/aston-villa.png',
  'Bournemouth': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bournemouth.png',
  'Brentford': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/brentford.png',
  'Brighton': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/brighton.png',
  'Chelsea': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/chelsea.png',
  'Crystal Palace': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/crystal-palace.png',
  'Everton': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/everton.png',
  'Fulham': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/fulham.png',
  'Ipswich': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ipswich.png',
  'Leicester City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/leicester-city.png',
  'Liverpool': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/liverpool.png',
  'Manchester City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/manchester-city.png',
  'Manchester United': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/manchester-united.png',
  'Newcastle': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/newcastle.png',
  'Nottingham Forest': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nottingham-forest.png',
  'Southampton': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/southampton.png',
  'Tottenham': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/tottenham.png',
  'West Ham': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/west-ham.png',
  'Wolves': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/wolves.png',
  'Birmingham City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/birmingham-city.png',
  'Blackburn Rovers': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/blackburn-rovers.png',
  'Bristol City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bristol-city.png',
  'Burnley': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/burnley.png',
  'Charlton Athletic': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/charlton-athletic.png',
  'Coventry City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/coventry-city.png',
  'Derby County': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/derby-county.png',
  'Hull City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/hull-city.png',
  'Leeds United': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/leeds-united.png',
  'Middlesbrough': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/middlesbrough.png',
  'Millwall': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/millwall.png',
  'Norwich City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/norwich-city.png',
  'Oxford United': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/oxford-united.png',
  'Portsmouth': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/portsmouth.png',
  'Preston North End': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/preston-north-end.png',
  'QPR': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/qpr.png',
  'Sheffield United': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sheffield-united.png',
  'Sheffield Wednesday': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sheffield-wednesday.png',
  'Stoke City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/stoke-city.png',
  'Sunderland': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sunderland.png',
  'Swansea City': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/swansea-city.png',
  'Watford': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/watford.png',
  'West Brom': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/west-brom.png',
  'Wrexham': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/wrexham.png',
  'Real Madrid': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/real-madrid.png',
  'Barcelona': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/barcelona.png',
  'Atletico Madrid': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-madrid.png',
  'Athletic Club': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/athletic-club.png',
  'Real Betis': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/real-betis.png',
  'Real Sociedad': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/real-sociedad.png',
  'Sevilla': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sevilla.png',
  'Valencia': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/valencia.png',
  'Villarreal': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/villarreal.png',
  'Celta Vigo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/celta-vigo.png',
  'Osasuna': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/osasuna.png',
  'Getafe': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/getafe.png',
  'Girona': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/girona.png',
  'Mallorca': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/mallorca.png',
  'Rayo Vallecano': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rayo-vallecano.png',
  'Espanyol': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/espanyol.png',
  'Elche': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/elche.png',
  'Levante': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/levante.png',
  'Deportivo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/deportivo.png',
  'Oviedo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/oviedo.png',
  'Bayern Munich': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bayern-munich.png',
  'Borussia Dortmund': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/borussia-dortmund.png',
  'RB Leipzig': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rb-leipzig.png',
  'Bayer Leverkusen': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bayer-leverkusen.png',
  'Eintracht Frankfurt': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/eintracht-frankfurt.png',
  'Borussia Monchengladbach': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/borussia-monchengladbach.png',
  'Stuttgart': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/stuttgart.png',
  'Wolfsburg': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/wolfsburg.png',
  'Hoffenheim': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/hoffenheim.png',
  'Freiburg': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/freiburg.png',
  'Werder Bremen': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/werder-bremen.png',
  'Union Berlin': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/union-berlin.png',
  'Augsburg': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/augsburg.png',
  'Mainz': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/mainz.png',
  'Koln': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/koln.png',
  'Heidenheim': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/heidenheim.png',
  'St Pauli': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/st-pauli.png',
  'Hamburg': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/hamburg.png',
  'Juventus': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/juventus.png',
  'Inter Milan': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/inter-milan.png',
  'AC Milan': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ac-milan.png',
  'Roma': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/roma.png',
  'Napoli': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/napoli.png',
  'Lazio': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lazio.png',
  'Atalanta': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atalanta.png',
  'Fiorentina': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/fiorentina.png',
  'Torino': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/torino.png',
  'Udinese': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/udinese.png',
  'Bologna': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bologna.png',
  'Genoa': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/genoa.png',
  'Verona': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/verona.png',
  'Cagliari': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cagliari.png',
  'Lecce': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lecce.png',
  'Parma': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/parma.png',
  'Sassuolo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sassuolo.png',
  'Como': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/como.png',
  'Cremonese': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cremonese.png',
  'Pisa': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/pisa.png',
  'PSG': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/psg.png',
  'Monaco': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/monaco.png',
  'Marseille': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/marseille.png',
  'Lyon': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lyon.png',
  'Lille': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lille.png',
  'Rennes': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rennes.png',
  'Nice': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nice.png',
  'Lens': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lens.png',
  'Strasbourg': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/strasbourg.png',
  'Nantes': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nantes.png',
  'Toulouse': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/toulouse.png',
  'Brest': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/brest.png',
  'Le Havre': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/le-havre.png',
  'Auxerre': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/auxerre.png',
  'Angers': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/angers.png',
  'Lorient': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lorient.png',
  'Metz': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/metz.png',
  'Paris FC': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/paris-fc.png',
  'Porto': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/porto.png',
  'Benfica': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/benfica.png',
  'Sporting CP': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sporting-cp.png',
  'Braga': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/braga.png',
  'Vitoria Guimaraes': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/vitoria-guimaraes.png',
  'Rio Ave': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rio-ave.png',
  'Famalicao': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/famalicao.png',
  'Gil Vicente': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/gil-vicente.png',
  'Casa Pia': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/casa-pia.png',
  'Santa Clara': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/santa-clara.png',
  'Estoril': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/estoril.png',
  'Moreirense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/moreirense.png',
  'Arouca': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/arouca.png',
  'Estrela Amadora': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/estrela-amadora.png',
  'Nacional Madeira': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nacional-madeira.png',
  'Alverca': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/alverca.png',
  'AVS': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/avs.png',
  'Tondela': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/tondela.png',
  'Ajax': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ajax.png',
  'PSV': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/psv.png',
  'Feyenoord': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/feyenoord.png',
  'AZ Alkmaar': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/az-alkmaar.png',
  'Twente': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/twente.png',
  'Utrecht': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/utrecht.png',
  'Heerenveen': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/heerenveen.png',
  'Groningen': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/groningen.png',
  'Sparta Rotterdam': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sparta-rotterdam.png',
  'NAC Breda': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nac-breda.png',
  'NEC': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nec.png',
  'Go Ahead Eagles': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/go-ahead-eagles.png',
  'Heracles': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/heracles.png',
  'PEC Zwolle': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/pec-zwolle.png',
  'Fortuna Sittard': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/fortuna-sittard.png',
  'Excelsior': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/excelsior.png',
  'Volendam': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/volendam.png',
  'Telstar': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/telstar.png',
  'River Plate': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/river-plate.png',
  'Boca Juniors': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/boca-juniors.png',
  'Racing Club': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/racing-club.png',
  'Independiente': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/independiente.png',
  'San Lorenzo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/san-lorenzo.png',
  'Estudiantes': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/estudiantes.png',
  'Newells': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/newells.png',
  'Rosario Central': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/rosario-central.png',
  'Talleres': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/talleres.png',
  'Velez': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/velez.png',
  'Lanus': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/lanus.png',
  'Huracan': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/huracan.png',
  'Belgrano': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/belgrano.png',
  'Godoy Cruz': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/godoy-cruz.png',
  'Defensa y Justicia': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/defensa-y-justicia.png',
  'Atletico Tucuman': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-tucuman.png',
  'Gimnasia La Plata': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/gimnasia-la-plata.png',
  'Banfield': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/banfield.png',
  'Union Santa Fe': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/union-santa-fe.png',
  'Tigre': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/tigre.png',
  'Platense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/platense.png',
  'Sarmiento': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sarmiento.png',
  'Penarol': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/penarol.png',
  'Nacional': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nacional.png',
  'Defensor Sporting': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/defensor-sporting.png',
  'Danubio': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/danubio.png',
  'Liverpool Montevideo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/liverpool-montevideo.png',
  'River Plate Uruguay': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/river-plate-uruguay.png',
  'Montevideo City Torque': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/montevideo-city-torque.png',
  'Boston River': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/boston-river.png',
  'Cerro': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cerro.png',
  'Cerro Largo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cerro-largo.png',
  'Colo Colo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/colo-colo.png',
  'Universidad de Chile': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/universidad-de-chile.png',
  'Universidad Catolica': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/universidad-catolica.png',
  'Audax Italiano': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/audax-italiano.png',
  'Cobresal': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cobresal.png',
  'Huachipato': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/huachipato.png',
  'Nublense': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nublense.png',
  'Palestino': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/palestino.png',
  'Union Espanola': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/union-espanola.png',
  'Union La Calera': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/union-la-calera.png',
  'OHiggins': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ohiggins.png',
  'Coquimbo Unido': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/coquimbo-unido.png',
  'Everton Chile': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/everton-chile.png',
  'Universitario': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/universitario.png',
  'Alianza Lima': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/alianza-lima.png',
  'Sporting Cristal': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sporting-cristal.png',
  'Melgar': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/melgar.png',
  'Cusco FC': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cusco-fc.png',
  'Cienciano': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cienciano.png',
  'Sport Huancayo': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sport-huancayo.png',
  'Atletico Grau': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-grau.png',
  'LDU Quito': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/ldu-quito.png',
  'Independiente del Valle': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/independiente-del-valle.png',
  'Barcelona SC': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/barcelona-sc.png',
  'Emelec': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/emelec.png',
  'Aucas': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/aucas.png',
  'El Nacional': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/el-nacional.png',
  'Delfin': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/delfin.png',
  'Macara': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/macara.png',
  'Deportivo Cuenca': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/deportivo-cuenca.png',
  'Tecnico Universitario': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/tecnico-universitario.png',
  'Olimpia': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/olimpia.png',
  'Cerro Porteno': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/cerro-porteno.png',
  'Libertad': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/libertad.png',
  'Guarani Paraguay': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/guarani-paraguay.png',
  'Nacional Paraguay': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/nacional-paraguay.png',
  'Sportivo Luqueno': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/sportivo-luqueno.png',
  'Atletico Nacional': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/atletico-nacional.png',
  'Independiente Medellin': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/independiente-medellin.png',
  'America de Cali': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/america-de-cali.png',
  'Deportes Tolima': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/deportes-tolima.png',
  'Deportivo Cali': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/deportivo-cali.png',
  'Millonarios': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/millonarios.png',
  'Junior': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/junior.png',
  'Santa Fe': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/santa-fe.png',
  'Once Caldas': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/once-caldas.png',
  'Deportivo Pereira': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/deportivo-pereira.png',
  'Bolivar': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/bolivar.png',
  'The Strongest': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/the-strongest.png',
  'Always Ready': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/always-ready.png',
  'Blooming': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/blooming.png',
  'Oriente Petrolero': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/oriente-petrolero.png',
  'Wilstermann': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/wilstermann.png',
  'Aurora': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/aurora.png',
  'Guabira': 'https://raw.githubusercontent.com/enzomkt-debug/futebol-agent/main/assets/logos/guabira.png',
}

module.exports = LOGOS
