[phases.setup]
nixPkgs = ["nodejs", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "fontconfig", "dejavu_fonts", "freetype"]

[phases.install]
cmds = ["npm install", "npm rebuild canvas", "fc-cache -fv"]

[start]
cmd = "node index.js"